### ISSUE TITLE
Using depricated version of Numpy

### ISSUE THREAD

**Issue by manjush3v** [fracpete/python-weka-wrapper#23]
While trying to install in fedora using pip, I found following warning and error messages  ->

/usr/lib64/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]

 #warning "Using deprecated NumPy API, disable it by " \

  ^

_javabridge.c:342:17: fatal error: jni.h: No such file or directory

 #include "jni.h"

                 ^

compilation terminated.

error: command 'gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools;__file__='/tmp/pip_build_root/javabridge/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-n6PFgI-record/install-record.txt --single-version-externally-managed failed with error code 1 in /tmp/pip_build_root/javabridge
Storing complete log in /root/.pip/pip.log

**Comment by fracpete** [comment]
You might want to have a look at the Python3 port of the library:
https://github.com/fracpete/python-weka-wrapper3
