### ISSUE TITLE
set_class_index(self,index)

### ISSUE THREAD

**Issue by tarun6006** [fracpete/python-weka-wrapper#35]
how about adding below mentioned function in 
weka.core.dataset.py ??? why is such function not available is python when it's available in java
i'm just curious why it's not available , i'll immediately close this issue if you want.

def set_class_index(self,index):
        """
        Sets the index value as class attribute (convenience method).
        """
        self.class_index = index

**Comment by fracpete** [comment]
Why would I duplicate the functionality of the ```class_index``` property, which allows you to ```set``` and ```get``` the class index? Much cleaner and Pythonic approach.
