### ISSUE TITLE
Create Instances from "Scratch"

### ISSUE THREAD

**Issue by charleslparker** [fracpete/python-weka-wrapper#36]
Thanks for the excellent project, which looks like it will work nicely for me except for one thing:  I need to be able to create some `weka.core.Instances` from, say, a python list of lists.  I'm happy to go through and create all the `attribute`s and whatnot by hand, but it doesn't look like there's an easy way to do this.

Is the only natural way of creating a training set through the `loader` methods (which would in general mean writing the dataset out to file then reading it back in), or is ther another way?

**Comment by fracpete** [comment]
pww just wraps around WEKA code. Before you can create a dataset, you need to create the attributes. Since each attribute is defined differently - nominal and relational attributes need additional information at instantiation time - this isn't that easy. If your data is purely numeric, then it would be possible, to use list of lists (or a numpy matrix) to create the Instances object.

**Comment by charleslparker** [comment]
> Since each attribute is defined differently - nominal and relational attributes need additional information at instantiation time - this isn't that easy.

Right - I've done all of this in Java before; I'm quite familiar with the Weka API.  It just didn't look to me like you've exposed the Java constructor for `Instances` anywhere in `python/weka/core.dataset.py`.  That is, the wrapper class assumes an already-created Java object as input (or am I missing something?)

Is there an easy way for me to instantiate an empty version of that object, then specify attributes?

Again, thanks for all of this!

**Comment by fracpete** [comment]
Rather than having a cluttered constructor (Python is sometimes not great to achieve polymorphism), I added a class method called `create_instances` to the `Instances` class. See also the example [here](https://github.com/fracpete/python-weka-wrapper-examples/blob/master/src/wekaexamples/core/dataset.py) (search for `create dataset` comment).

**Comment by charleslparker** [comment]
That's exactly what I was looking for.  Thanks again!

**Comment by slychief** [comment]
I would also like to thank you for this wrapper. It is perfect for reproduceable research!

Concerning the question raised and answered in this thread:

I have created the weka Instances object and filled it with numeric data from a numpy array. The new question is, how can I assign class labels to the created instances?

**Comment by charleslparker** [comment]
Hey @slychief - @fracpete might have more to say, but what I do is fill the `Instances` with all values, including the class attribute, then set the `Instances.class_attribute` property.  Classifiers in weka know about it and will use that attribute as the target.

https://github.com/fracpete/python-weka-wrapper/blob/master/python/weka/core/dataset.py#L159

**Comment by fracpete** [comment]
Weka does not separate data and labels, they're all part of the dataset. Hence the assignment of the class attribute after creating the dataset structure.

**Comment by slychief** [comment]
Thanks for the fast repsonse. I am still struggling with adding string values as class labels. The dataset should look like this:

0.108569,0.046317,0.606688,class_a
0.208555,0.894589,0.440304,class_b
0.547066,0.546897,0.914485,class_c

This is my code:

```python

# random float matrix
import numpy as np

numpy_data = np.random.rand(3,3)

# prepare instances
from weka.core.dataset import Instances, Attribute, Instance

# define attributes
num_att1  = Attribute.create_numeric("attr1")
num_att2  = Attribute.create_numeric("attr2")
num_att3  = Attribute.create_numeric("attr3")
class_att = Attribute.create_string("class")

# create weka data container
instances = Instances.create_instances(
                name     = "my_numpy_data",                # the relation name
                atts     = [num_att1, num_att2, num_att3, class_att], # the list of attributes to use for the dataset
                capacity = numpy_data.shape[0]             # how many data rows to reserve initially (see compactify)
            )

    


# copy numpy data
for i in range(numpy_data.shape[0]):
    
    # supplying string values to create_instance is not supported
    inst = Instance.create_instance(numpy_data[i,:])
    instances.add_instance(inst)

for i in range(numpy_data.shape[0]):
    
    inst = instances.get_instance(i)
    inst.set_string_value(3, 'test')
    
instances.class_is_last()

```

the statement inst.set_string_value(3, 'test') raises the following exception:

```
---------------------------------------------------------------------------
JavaException                             Traceback (most recent call last)
<ipython-input-53-5eb33ca787c5> in <module>()
     32 
     33     inst = instances.get_instance(i)
---> 34     inst.set_string_value(3, 'test')
     35 
     36 instances.class_is_last()

C:\Anaconda\lib\site-packages\weka\core\dataset.pyc in set_string_value(self, index, s)
    658         :type s: str
    659         """
--> 660         return self.__set_string_value(index, javabridge.get_env().new_string(s))
    661 
    662     def get_string_value(self, index):

C:\Anaconda\lib\site-packages\javabridge\jutil.py in fn(*args)
    850             x = env.exception_occurred()
    851             if x is not None:
--> 852                 raise JavaException(x)
    853             return result
    854     else:

JavaException: 3
```

**Comment by charleslparker** [comment]
Hey @slychief - Unless I'm much mistaken, one problem is that `inst = Instance.create_instance(numpy_data[i,:])` creates an instance that has length of three.  That is, even though you've added four attributes to your `Instances`, you also need to have a four-value list when you create each `Instance`.  If you look a little further up your stack trace you should see Java generating an `ArrayIndexOutOfBoundsException`.

As you mention, you can't pass in a string there, and here's the other problem:  A variable with a small fixed number of values, like your `class` variable, is a nominal attribute in weka, not a string.  So create a nominal attribute for your class and then pass the *index* of the value you want to `create_instance`, like so:

```python
class_values = ["a", "b", "c"]

# define attributes
num_att1  = Attribute.create_numeric("attr1")
num_att2  = Attribute.create_numeric("attr2")
num_att3  = Attribute.create_numeric("attr3")
class_att = Attribute.create_nominal("class", class_values)

# create weka data container
instances = Instances.create_instances(
                name     = "my_numpy_data",
                atts     = [num_att1, num_att2, num_att3, class_att],
                capacity = numpy_data.shape[0]
                )

inst = Instance.create_instance([1, 2, 3, class_values.index("a")])
instances.add_instance(inst)
```

Then you should have:
```ipython
In [28]: instances
Out[28]: 
@relation my_numpy_data

@attribute attr1 numeric
@attribute attr2 numeric
@attribute attr3 numeric
@attribute class {a,b,c}

@data
1,2,3,a
```

**Comment by slychief** [comment]
Hi @charleslparker! Of course, this makes sense. I wasn't aware that the class variable is nominal. Thanks a lot!
