### ISSUE TITLE
Configuring Time Series Forecasting

### ISSUE THREAD

**Issue by ddm7018** [fracpete/python-weka-wrapper#37]
Any clue on how to install the required packages for time series forecasting. 

I  tried download the zip file and adding the package. But when I run I still get errors. 

```
>>> import weka.classifiers.timeseries
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named timeseries
```

**Comment by fracpete** [comment]
Usually, you install packages through the Weka package manager GUI (from inside Weka) or using the exposed [package manager API](http://pythonhosted.org/python-weka-wrapper/api.html#packages).

**Comment by ddm7018** [comment]
I see the timeSeriesForecasting module installed inside python weka wrapper but I don't have a clue how to call it.

**Comment by fracpete** [comment]
The timeseries plugin introduces a new class hierarchy (`weka.classifiers.timeseries.TSForecaster`) and is not directly available via a convenient wrapper in python-weka-wrapper.
What you could do is wrap it inside an `OptionHandler` object (imported from module `weka.core.classes`) and then use the `jwrapper` property to access the underlying Java object directly.

**Comment by ddm7018** [comment]
I wanted to share a solution in case someone ran into a similar issue
```
from javabridge import JWrapper
import javabridge
import weka.core.jvm as jvm
jvm.start()
a = JWrapper(javabridge.make_instance("weka/classifiers/timeseries/WekaForecaster", "()V"))
```

**Comment by Bluesman79** [comment]
Hi ddm7018,

would you mind please give an example of your solution? say that I have a csv file of only one att: "Alpha" with 100 instances, I would like to use the AlternatingModelTree as my learner and I want just one prediction (of the 101 instance). Do you have any idea how I am going to do that?

thanks in advance

**Comment by shikarkhane** [comment]
I installed Forecaster plugin on my local Weka installation and then used it like this
`import weka.core.jvm as jvm

from weka.classifiers import Classifier
import weka.core.packages as packages
from weka.core.converters import Loader


jvm.start(packages=True, max_heap_size="512m")

packages.refresh_cache()

cls = Classifier(classname="weka.classifiers.timeseries.HoltWinters",
                 options=["-alpha", "0.2", "-beta", "0.2", "-gamma", "0.2", "cycle-length", "1"])
print(cls.options)


loader = Loader(classname="weka.core.converters.ArffLoader")
data = loader.load_file("/your/file/path/activeUsers.arff")

print 'Training data: ------------------------'
print(data)

data.class_is_last()

cls.build_classifier(data)

print 'Predictions: ------------------------'
for i in range(90):
    forecast = cls.jwrapper.forecast()
    print (forecast)
    cls.jwrapper.updateForecaster(forecast)

jvm.stop()`
