### ISSUE TITLE
number of selected attributes is wrong in this example

### ISSUE THREAD

**Issue by srvanrell** [fracpete/python-weka-wrapper#38]
it should be 5 instead of 4, am I right?

    data = loader.load_file(data_dir + "vote.arff")
    data.class_is_last()

    from weka.attribute_selection import ASSearch, ASEvaluation, AttributeSelection
    search = ASSearch(classname="weka.attributeSelection.BestFirst", options=["-D", "1", "-N", "5"])
    evaluator = ASEvaluation(classname="weka.attributeSelection.CfsSubsetEval", options=["-P", "1", "-E", "1"])
    attsel = AttributeSelection()
    attsel.search(search)
    attsel.evaluator(evaluator)
    attsel.select_attributes(data)

    print("# attributes: " + str(attsel.number_attributes_selected))
    print("selected: " + str(attsel.selected_attributes))
    print("result string:\n" + attsel.results_string)

**Comment by fracpete** [comment]
5 including the class attribute, 4 excluding. The array that is returned by Weka contains the class attribute (#16).

**Comment by srvanrell** [comment]
Sorry, Peter, I noticed it late. 
The enumeration used in weka vs the one used in python (zero based) confused me.
output wrapper: [ 2  3  9 10 16]
output in results string: 3,4,10,11
