### ISSUE TITLE
Evaluating on provided set of instances

### ISSUE THREAD

**Issue by kliegr** [fracpete/python-weka-wrapper#39]
I am trying to evaluate a model on a provided set of instances. This boils down to invoking [evaluateModel](http://weka.sourceforge.net/doc.dev/weka/classifiers/Evaluation.html#evaluateModel%28weka.classifiers.Classifier,%20weka.core.Instances,%20java.lang.Object...%29) static method from Weka.

While this is not supported in python-weka-wrapper, creating such call should not be difficult. I tried the following:

    classifier = Classifier(classname="weka.classifiers.trees.J48", options=["-C", "0.3"])
    classifier.build_classifier(train)
    ...

    javabridge.static_call(
            "Lweka/classifiers/Evaluation;", "evaluateModel",
            "(Lweka/classifiers/Classifier;Lweka/core/Instances;[Ljava/lang/Object;)[D",
            classifier.jobject, test.jobject)

where 
`test` is of type weka.core.Instances
`classifier` is of type Classifier

 I am getting the following error: `Could not find method name = evaluateModel with signature = (Lweka/classifiers/Classifier;Lweka/core/Instances;[Ljava/lang/Object;)[D`

I've also tried explicitly adding the empty third parameter with None or [], which did not help.

Signature looks fine to me:
* Lweka/classifiers/Classifier; - Classifier object
* Lweka/core/Instances; - instances object
* [Ljava/lang/Object; - varargs
* [D - array of doubles return type

Thanks for any pointers

**Comment by fracpete** [comment]
If you look at the Javadoc of the `weka.classifiers.Evaluation` class, then you'll find that there is no such static method. You are referring to the non-static one instead. This one is alread available as `test_model` method from Python.
