### ISSUE TITLE
Error in example.rst

### ISSUE THREAD

**Issue by kliegr** [fracpete/python-weka-wrapper#40]
Thanks for the help on the previous issue. 
I believe I spotted a possible error in this [section](https://github.com/fracpete/python-weka-wrapper/blob/b92a37af0da072e8b4d719f3634d5076e3eec87a/doc/source/examples.rst#cross-validate-filtered-classifier-and-print-evaluation-and-display-roc) of the documentation:

    evl.crossvalidate_model(cls, data, 10, Random(1))
should be 

    evl.crossvalidate_model(fc, data, 10, Random(1))

**Comment by fracpete** [comment]
Fixed. Thanks for reporting!
