### ISSUE TITLE
java.lang.NoSuchFieldError: TAGS_EVALUATION when using MultiSearch

### ISSUE THREAD

**Issue by kliegr** [fracpete/python-weka-wrapper#41]
Hello,

When initializing MultiSearch exactly according to the [docs](http://pythonhosted.org/python-weka-wrapper/examples.html#parameter-optimization-multisearch), I get

    Exception in thread "Thread-0" java.lang.NoSuchFieldError: TAGS_EVALUATION
    Traceback (most recent call last):
    File "crossvalfolds-weka.py", line 131, in <module>
    "-num-slots", "1", "-S", "1"])
    File "/home/tomas/anaconda/lib/python2.7/site-packages/weka/classifiers.py", line 404, in __init__
    self.tags_evaluation = Tags.get_tags("weka.classifiers.meta.MultiSearch", "TAGS_EVALUATION")
    File "/home/tomas/anaconda/lib/python2.7/site-packages/weka/core/classes.py", line 1356, in    get_tags
    return Tags(jobject=javabridge.get_static_field(classname, field, "[Lweka/core/Tag;"))
    File "/home/tomas/anaconda/lib/python2.7/site-packages/javabridge/jutil.py", line 956, in get_static_field
    raise JavaException(jexception)
    javabridge.jutil.JavaException: TAGS_EVALUATION

My code

    from weka.classifiers import MultiSearch
    ....
    multi = MultiSearch(
      options=["-sample-size", "100.0", "-initial-folds", "2", "-subsequent-folds", "2",
	      "-num-slots", "1", "-S", "1"])

MultiSearch freshly installed with

    java -cp /usr/local/lib/python2.7/dist-packages/weka/lib/weka.jar weka.core.WekaPackageManager -install-package https://github.com/fracpete/multisearch-weka-package/releases/download/v2016.1.14/multisearch-2016.1.14.zip

Other possibly relevant installation steps:

    pip install javabridge
    pip install python-weka-wrapper

Weka version 3.7.13

Thanks!

**Comment by fracpete** [comment]
The multi-search package got a bit more dynamic with the recent releases, making it possible to swap out metrics (for instance when using for other frameworks such as [MEKA](http://meka.sf.net/). That unfortunately broke the MultiSearch wrapper class in the python-weka-wrapper project.
Hence I released new versions of both projects, to make them work together again:
* python-weka-wrapper: 0.3.4
* multi-search: 2016.1.15
