### ISSUE TITLE
MultiSearch prop value for J48 decision tree parameters

### ISSUE THREAD

**Issue by kliegr** [fracpete/python-weka-wrapper#42]
I am trying to optimize "C" and "R" parameters of [J48](http://weka.sourceforge.net/doc.dev/weka/classifiers/trees/J48.html). It seems I am not getting right the corresponding property values. For "C" I  use  "classifier.C", since the example [SMOreg](https://github.com/fracpete/python-weka-wrapper/blob/614f01ae36ef9246b814d4e46d96804a1dd36201/doc/source/examples.rst#parameter-optimization---multisearch), has also "C" parameter (same command line [option "-C"](http://weka.sourceforge.net/doc.dev/weka/classifiers/functions/SMOreg.html)), which is referred to with "classifier.C":

      mparam.prop = "classifier.C"
      lparam.prop = "classifier.R"

With the setting above, I get the following error from the build_classifier() method

    java.beans.IntrospectionException: Method not found: isC
	at java.beans.PropertyDescriptor.<init>(PropertyDescriptor.java:107)
	at java.beans.PropertyDescriptor.<init>(PropertyDescriptor.java:71)
	at weka.core.PropertyPath.find(PropertyPath.java:386)
	at weka.core.PropertyPath.find(PropertyPath.java:410)
	at weka.core.SetupGenerator.setup(SetupGenerator.java:592)
	at weka.classifiers.meta.MultiSearch.findBest(MultiSearch.java:1444)
	at weka.classifiers.meta.MultiSearch.buildClassifier(MultiSearch.java:1481)

Same exception for isR.

The full  code

    multi = MultiSearch(
	options=["-sample-size", "100.0", "-initial-folds", "2", "-subsequent-folds", "2",
	      "-num-slots", "1", "-S", "1"])
	multi.evaluation = "CC"
	mparam = MathParameter()
	mparam.prop = "classifier.C"
	mparam.minimum = 0.1
	mparam.maximum = 0.5
	mparam.step = 0.1
	mparam.base = 10.0
	mparam.expression = "pow(BASE,I)"
	lparam = ListParameter()
	#Reduced error pruning
	lparam.prop = "classifier.R"
	lparam.values = [True, False]
	multi.parameters = [mparam, lparam]
	clOpt = Classifier(classname="weka.classifiers.trees.J48", options=["-C", "0.3"])
	multi.classifier = clOpt
	multi.build_classifier(train)

In the largely c&p code above from the example doc, it is not clear to me what is the role of the multi.evaluation  and mparam.expression, but I doubt it has anything to do with the error.

Thanks for your continuing support.

**Comment by fracpete** [comment]
Please use the mailing list for questions ("forum" section in the README.md), not the issue tracker (reserved for bugs).
