### ISSUE TITLE
Loader "loads" a non existent file without warning

### ISSUE THREAD

**Issue by srvanrell** [fracpete/python-weka-wrapper#44]
Below it is a minimal example [(also in loaderBug.py)](https://github.com/srvanrell/libsvm-weka-python) of what I think it is a bug.
The example loads an existent file (into `trainData`) and a non existent file (into `testData`). 
However both datasets contains `trainData` information (the example prints both `num_instances`, and they are unexpectedly the same). 

```
#!/usr/bin/python
# -*- coding: utf-8 -*-

import weka.core.jvm as jvm
from weka.core.converters import Loader

jvm.logger.setLevel(jvm.logging.INFO)
jvm.start()

loader = Loader(classname="weka.core.converters.ArffLoader")
trainData = loader.load_file('segment-challenge.arff')
testData = loader.load_file('this-file-not-exist')  # silent fail

print(trainData.num_instances)  # True answer (1500)
print(testData.num_instances)   # False answer (1500)

jvm.stop()
```

**Comment by fracpete** [comment]
That seems to a be Weka *feature*. I've added a check to the `load_file` method to raise an exception if the file does not exist.
