### ISSUE TITLE
Create an instance from a numpy array and classify it

### ISSUE THREAD

**Issue by ignasi42** [fracpete/python-weka-wrapper#46]
Hello,
I would like to, given a numpy array (a vector, with a number of attribute values), classify it.
However, I don't know how to convert that vector into an instance and pass it to the classifier:
I get an error saying 

> "JavaException: Instance doesn't have access to a dataset!"

It seems I have to add that instance to a dataset, but I don't know why. Do I have to create a fake dataset with only one instance and then classify it? That instance won't have a class either.
This is how my code looks like:

```
loader = Loader(classname="weka.core.converters.ArffLoader")    
data = loader.load_file(TRAINING_ARFF)
data.class_is_last()

cls = Classifier(classname="weka.classifiers.trees.J48", options = ["-C", "0.3", "-M", "10"])
cls.build_classifier(data)

instance_vector = Instance.create_instance(numpy_vector)

class = cls.classify_instance(instance_vector)
```

Many thanks in advance!
Cheers,
Ignasi

**Comment by fracpete** [comment]
An `Instance` object needs access to an `Instances` object as this holds the `Attribute` definitions (numeric, nominal, date, string, relational). You can use the `Instance.dataset` property to set the dataset structure. Just make sure that you have the correct number of attributes (incl. class attribute!) when creating the new Instance object. Just use `0` as dummy value for the class label (ie using the first label).

**Comment by ignasi42** [comment]
Hi @fracpete,
Thank you very much, I got it. Now it's working find.
I just added 
`instance_vector.dataset = data`  
before 
`class = cls.classify_instance(instance_vector)`
and now it works perfectly.
Cheers!
Ignasi
