### ISSUE TITLE
Example issues in windows

### ISSUE THREAD

**Issue by arita37** [fracpete/python-weka-wrapper#50]
When running this code, 
```
from weka.classifiers import Classifier
cls = Classifier(classname="weka.classifiers.trees.J48")
print(cls.to_help())
```

I have this error message:
`cannot find classname attribute for Classifier __init__`

It seems it cannot load the class in Python

**Comment by fracpete** [comment]
Please provide more details:
* Windows version (run `ver` in the command prompt)
* Java version (run `java -version` in the command prompt)
* Python version (run `python -V` in the command prompt)
* python-weka-wrapper version that you installed (also, Python 2.7 or Python 3?)
* javabridge version that you installed

Also, what is the output in the command prompt when starting up the JVM using `jvm.start()` in your script?

**Comment by fracpete** [comment]
No further information provided, hence closed.
