### ISSUE TITLE
I want to load model that trained in WEKA

### ISSUE THREAD

**Issue by chanapong3** [fracpete/python-weka-wrapper#59]
I want to load model that trained in WEKA.(.model) file
And I want to use it in python. 
Do you have any example or any guideline ? 

Step that in my mind is
1.load model file in python
2.load csv or dataframe(pandas) in to python ( This step no problems). (That i want to get prediction)
3. Get 1 line of data csv or dataframe that contain some of features
(each of row contains 1 set of DATA) that was  train in WEKA before.(But new value)
4.Get Prediction in python.
Thank a lot

**Comment by fracpete** [comment]
Here is an example for performing serialization and deserialization:
https://github.com/fracpete/python-weka-wrapper-examples/blob/master/src/wekaexamples/core/serialization.py
