### ISSUE TITLE
issue of setting up on Pycharm

### ISSUE THREAD

**Issue by yifeilyf** [fracpete/python-weka-wrapper#60]
Hi,

`import weka.core.jvm as jvm
from weka.core.converters import Loader
from weka.experiments import ResultMatrix, Tester

jvm.start()

data_file = "kddcup.data_10_percent_corrected_10000_samples.arff"
loader = Loader(classname="weka.core.converters.ArffLoader")
data = loader.load_file(data_file)

print(data)
jvm.stop()`

I put these codes on Spyder, and works well. When I try these on Pycharm after installing python-weka-wrapper3 on it, there are some errors. The following are what I got. Please have a look.

`/usr/local/bin/python3.4 /Users/yifeiluo/Documents/Curtin/Y1S2/COMP5009/w3/lab/demo/demo.py
DEBUG:weka.core.jvm:Adding bundled jars
DEBUG:weka.core.jvm:Classpath=['/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/javabridge/jars/rhino-1.7R4.jar', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/javabridge/jars/runnablequeue.jar', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/javabridge/jars/cpython.jar', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/weka/lib/python-weka-wrapper.jar']
DEBUG:weka.core.jvm:MaxHeapSize=default
DEBUG:weka.core.jvm:Package support disabled
DEBUG:javabridge.jutil:Creating JVM object
DEBUG:javabridge.jutil:Launching VM in non-python thread
DEBUG:javabridge.jutil:Attaching to VM in monitor thread
DEBUG:javabridge.jutil:Signalling caller
Exception in thread "Thread-1" Failed to get class Lweka/core/WekaPackageManager;
java.lang.NoClassDefFoundError: Lweka/core/WekaPackageManager;
Caused by: java.lang.ClassNotFoundException: weka.core.WekaPackageManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Traceback (most recent call last):
  File "/Users/yifeiluo/Documents/Curtin/Y1S2/COMP5009/w3/lab/demo/demo.py", line 13, in <module>
    jvm.start()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/weka/core/jvm.py", line 122, in start
    False)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/javabridge/jutil.py", line 934, in static_call
    fn = make_static_call(class_name, method_name, sig)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/javabridge/jutil.py", line 908, in make_static_call
    raise JavaException(jexception)
javabridge.jutil.JavaException: Lweka/core/WekaPackageManager;
`
Kind Regards,
Yifei

**Comment by fracpete** [comment]
Are you using the same virtual environment for both, Spyder and PyCharm?

**Comment by yifeilyf** [comment]
Hi,
Spyder is under Anaconda with python 3.6, and Pycharm is under my system path with python 3.7. However, for Anaconda, I did nothing about settings, and it works automatically. Under python 3.7, I install several packages. The following image shows what I did. Please have a look. I do not know what I miss.
![image](https://user-images.githubusercontent.com/12167107/44374573-7ded2f00-a521-11e8-8cae-a5828a1853ae.png)

Cheers

**Comment by fracpete** [comment]
Just use your working Anaconda environment:
https://stackoverflow.com/questions/42746732/use-conda-environment-in-pycharm

**Comment by fracpete** [comment]
BTW I've been mainly using Python 3.5, on Linux

**Comment by yifeilyf** [comment]
Hi,

I switch back to Anaconda with python 3.5, and errors are different. It may be related to javabridge.

Cheers
`/Users/yifeiluo/.conda/envs/prac2_sample_code.py/bin/python /Users/yifeiluo/Documents/Curtin/Y1S2/COMP5009/w3/lab/demo/prac2_sample_code.py
Traceback (most recent call last):
  File "/Users/yifeiluo/Documents/Curtin/Y1S2/COMP5009/w3/lab/demo/prac2_sample_code.py", line 23, in <module>
    import weka.core.jvm as jvm
  File "/Users/yifeiluo/.conda/envs/prac2_sample_code.py/lib/python3.5/site-packages/weka/core/jvm.py", line 17, in <module>
    import javabridge
  File "/Users/yifeiluo/.conda/envs/prac2_sample_code.py/lib/python3.5/site-packages/javabridge/__init__.py", line 38, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "/Users/yifeiluo/.conda/envs/prac2_sample_code.py/lib/python3.5/site-packages/javabridge/jutil.py", line 157, in <module>
    import javabridge._javabridge as _javabridge
ImportError: dlopen(/Users/yifeiluo/.conda/envs/prac2_sample_code.py/lib/python3.5/site-packages/javabridge/_javabridge.cpython-35m-darwin.so, 2): Symbol not found: _kCFAllocatorDefault
  Referenced from: /Users/yifeiluo/.conda/envs/prac2_sample_code.py/lib/python3.5/site-packages/javabridge/_javabridge.cpython-35m-darwin.so
  Expected in: flat namespace
 in /Users/yifeiluo/.conda/envs/prac2_sample_code.py/lib/python3.5/site-packages/javabridge/_javabridge.cpython-35m-darwin.so

Process finished with exit code 1`

**Comment by fracpete** [comment]
I've only used Anaconda on Windows (and I don't have access to a Mac). Can you please record (and post) all the steps when creating a fresh anaconda environment with python-weka-wrapper (for Python 3.5)? Simply to see whether the error can be replicated. Also post the output of "pip freeze" once done.

**Comment by yifeilyf** [comment]
Hi,
Please have a look the video
Cheers

[record.mp4.zip](https://github.com/fracpete/python-weka-wrapper/files/2308791/record.mp4.zip)

**Comment by fracpete** [comment]
Sorry for not being clear. I meant the commands in text format, so I can easily copy/paste them.

**Comment by yifeilyf** [comment]
Sorry for that. The following is what I got after pip freeze.
` pip freeze
astroid==1.6.5
backports.functools-lru-cache==1.5
configparser==3.5.0
enum34==1.1.6
futures==3.2.0
isort==4.3.4
lazy-object-proxy==1.3.1
mccabe==0.6.1
pylint==1.9.3
singledispatch==3.4.0.3
six==1.11.0
wrapt==1.10.11
`

**Comment by fracpete** [comment]
The `pip freeze` command must be done in the environment. Otherwise, I don't see what packages you've installed. ;-)

**Comment by yifeilyf** [comment]
I just notice that pycharm internal terminal environment is different with python interpreter that i created. Could you tell me how to switch internal terminal environment. 
Cheers
<img width="269" alt="image" src="https://user-images.githubusercontent.com/12167107/44496463-3abcc880-a6a7-11e8-84ad-82cdf29d3a16.png">

**Comment by fracpete** [comment]
Each run configuration defines what interpreter is being used.
![interpreter](https://user-images.githubusercontent.com/1026180/44497162-fb54a300-a6cb-11e8-8ffe-4b16a483aeae.png)

**Comment by yifeilyf** [comment]
My run configuration is right, how could I get installed packages by pip freeze since terminal under pycharm comes with default system version. You mentioned "The pip freeze command must be done in the environment. " Now, pycharm internal terminal comes with system default python 3.7 not the one that I created with anaconda python 3.5. How could I switch to that environment? Sorry for my bad English. I think my problem is same with this "https://stackoverflow.com/questions/41237346/pycharms-terminal-doesnt-change-the-python-version-corresponding-to-python-ver". 
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/12167107/44497726-8bcfbb00-a6ad-11e8-8392-85b43592d7f0.png">

<img width="709" alt="image" src="https://user-images.githubusercontent.com/12167107/44497745-a1dd7b80-a6ad-11e8-8a88-c0f25d88d1dc.png">

**Comment by fracpete** [comment]
Why are you trying to run `pip freeze` from PyCharm? Just run the command from a regular terminal after activating the environment.

**Comment by yifeilyf** [comment]
Thank you.
This is what I got
`(anacondaPy3.5) MPBYLYF:~ yifeiluo$ pip freeze
certifi==2018.8.13
cycler==0.10.0
javabridge==1.0.17
kiwisolver==1.0.1
matplotlib==2.2.3
mkl-fft==1.0.4
mkl-random==1.0.1
numpy==1.15.0
pyparsing==2.2.0
python-dateutil==2.7.3
python-weka-wrapper3==0.1.4
pytz==2018.5
six==1.11.0
tornado==5.1
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(anacondaPy3.5) MPBYLYF:~ yifeiluo$`

**Comment by fracpete** [comment]
What post are you referring to?

**Comment by yifeilyf** [comment]
https://github.com/LeeKamentsky/python-javabridge/issues/136
Sorry for that

**Comment by fracpete** [comment]
Maybe instead of using anaconda, try setting up a virtual environment. See this post here:
https://stackoverflow.com/questions/50184736/in-mac-osx-weka-does-not-recognize-python-possible-python-conflict/50185124#50185124
Please note, that I don't have access to a Mac, so I can't verify this.

**Comment by yifeilyf** [comment]
Still not working. But I setup the whole environment on Lubuntu and it works. Thank you so much for your help.
Cheers

**Comment by fracpete** [comment]
Sorry, that we couldn't get it to work on OSX. Macs are always a bit different...
