### ISSUE TITLE
How to getAssociationRules()

### ISSUE THREAD

**Issue by marcwell** [fracpete/python-weka-wrapper#63]
Hello,

I trained an apriori Associator

`associator = Associator(classname="weka.associations.Apriori", options=[])`
`associator.build_associations(data)`
`print(associator)`

and verified that I get the same results as in Java. Now I wanted to get the association rules, as I'd do in Java with `rules = apriori.getAssociationRules();`. How can I do that in Python?

Thanks.

**Comment by fracpete** [comment]
Please use the mailing list for questions:
https://groups.google.com/forum/#!forum/python-weka-wrapper

pww just wraps the major interfaces of Weka. I've extended the following example, which shows how access underlying Java methods/objects like `getAssociationRules()`:
https://github.com/fracpete/python-weka-wrapper-examples/blob/master/src/wekaexamples/associations/apriori_output.py
